language: csharp
mono: none
dotnet: 2.1.403
script:
  - dotnet restore
  - dotnet build
  - dotnet test tests/Application.Tests
notifications: 
  email:
    - neil@intapoint.com
deploy:
  provider: azure_web_apps
  verbose: true